In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import gradio as gr
from PIL import Image
from on_field_gear_compliance_hackathon.models import predict

/home/aditya_rustagi_farmart_co/.local/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/aditya_rustagi_farmart_co/.conda/envs/content-moderation/lib/python3.9/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
2023-11-07 06:58:28.512109: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-07 06:58:28.512185: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-07 06:58:28.512224: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to regist

initializing model


In [3]:
def check_authenticity(image) :

    print(type(image))

    count = predict.contrastive_reply(image, mode='count_people')
    print(type(count))
    if not count == 'a photo with 1 person' :
        return "Validation Failed, provided does not have only one person"


    helmet = predict.contrastive_reply(image, mode='helmet')
    print(helmet)
    if not helmet == 'a person wearing helmet' :
        return "The person is not wearing helmet"

    return helmet

In [4]:
with gr.Blocks() as demo :
    
    gr.Markdown('On site gear compliance demo')
    with gr.Tab('Detect helmet') :
        helmet_image = gr.Image()
        helmet_output = gr.Text()
        helmet_button = gr.Button("Detect Helmet")
        
    with gr.Tab('Recognize individual') :
        recognize_image = gr.Image()
        recognize_output = gr.Image(label="Output Box")
        recognize_button = gr.Button("Fetch Name")
        
    with gr.Tab('Add individual') :
        add_image = gr.Image()
        add_name = gr.Text()
        add_output = gr.Text()
        add_button = gr.Button("Add")


    helmet_button.click(fn=check_authenticity, inputs=helmet_image, outputs = helmet_output)
    recognize_button.click(fn=predict.recognize, inputs=recognize_image, outputs=recognize_output)
    add_button.click(fn=predict.add_face, inputs=[add_image, add_name], outputs=add_output)


In [5]:
demo.launch()

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


<class 'numpy.ndarray'>
tensor([[0.1450, 0.6085, 0.2465]], grad_fn=<SoftmaxBackward0>)
<class 'str'>
tensor([[0.1803, 0.8197]], grad_fn=<SoftmaxBackward0>)
a person not wearing helmet
<class 'numpy.ndarray'>
tensor([[0.1874, 0.7114, 0.1012]], grad_fn=<SoftmaxBackward0>)
<class 'str'>
tensor([[0.7940, 0.2060]], grad_fn=<SoftmaxBackward0>)
a person wearing helmet
<class 'numpy.ndarray'>
tensor([[0.1403, 0.8115, 0.0482]], grad_fn=<SoftmaxBackward0>)
<class 'str'>
tensor([[0.7915, 0.2085]], grad_fn=<SoftmaxBackward0>)
a person wearing helmet
There are  19  representations found in  representations_vgg_face.pkl


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The 

find function lasts  10.986637830734253  seconds
/home/aditya_rustagi_farmart_co/fmt/on_field_gear_compliance/data/verified_images/WhatsApp Image 2023-10-16 at 17.33.02.jpeg
3    /home/aditya_rustagi_farmart_co/fmt/on_field_g...
2    /home/aditya_rustagi_farmart_co/fmt/on_field_g...
1    /home/aditya_rustagi_farmart_co/fmt/on_field_g...
0    /home/aditya_rustagi_farmart_co/fmt/on_field_g...
Name: identity, dtype: object
3    0.389982
2    0.321571
1    0.304338
0    0.297934
Name: VGG-Face_cosine, dtype: float64
There are  19  representations found in  representations_vgg_face.pkl
find function lasts  0.3954887390136719  seconds
/home/aditya_rustagi_farmart_co/fmt/on_field_gear_compliance/data/verified_images/WhatsApp Image 2023-11-02 at 10.24.34.jpeg
2    /home/aditya_rustagi_farmart_co/fmt/on_field_g...
1    /home/aditya_rustagi_farmart_co/fmt/on_field_g...
0    /home/aditya_rustagi_farmart_co/fmt/on_field_g...
Name: identity, dtype: object
2    0.392905
1    0.281367
0    0.183563
N